### ISSUE TITLE
Module configuration svelte

### ISSUE THREAD

**Issue by djplaner** [djplaner/canvas-collections#161]
- [x] engage
- [ ] implement date component
- [x] module config banner component
- [x] module config representation choice
- [x] label and number
    - [x] auto num not reactive 
- [x] module config meta data component
- [x] module config FYI card config
- [x] HTML design and layout

**Comment by djplaner** [comment]
## Working on dates

### shoelace tabs

- [ ] get working with show/hide module configuration

### General

- [ ] restructure layout
- [ ] improve formatting
- [ ] Help
- [ ] Label and number
- [ ] ??

### Dates

Component created

- [ ] Modify start up to always ensure that date objects full exist, but empty if not set
- [ ] Much more in the code

### Banner

Everything

### Metadata

Everything

**Comment by djplaner** [comment]
# Developing form styles

Need a way to neatly set out form components - labels and inputs - [inspired by this](https://webdesign.tutsplus.com/tutorials/how-to-build-web-form-layouts-with-css-grid--cms-28776)

```html
<div class="cc-module-form">
  <span class="cc-module-label">
    <!-- all the stuff to display in the label column -->
  </span>
  <span class="cc-module-input">
    <!-- all the stuff to put in the input column -->
  </span>
</div>
```

```css

  .cc-module-form {
    display: grid;
    grid-template-columns: 8em 1fr;
    grid-gap: 1em;
  }

  .cc-module-label {
    grid-column: 1/ 2;
    text-align: right;
	margin-top: 0.4em;
  }

  .cc-module-input {
    grid-column: 2/ 3;
  }
```
